name: Test Chameleon Gradle

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v6

      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v6

      - name: setup jdk
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'microsoft'

      - name: 'Assemble with Gradle'
        run: |
          export BUILD_NUMBER=${{ github.run_number }}
          chmod +x ./gradlew
          ./gradlew assemble
